language: java
jdk:
  - oraclejdk8

before_install:
  - git clone https://${GH_REF}/piccuss.github.io.git
script:
  - mvn test

#after_script:
#  - cd piccuss.github.io/source/_posts/
#  - git checkout -b hexo origin/hexo
#  - git add .
#  - git commit -m"Travis auto commit"
#  - git push --force "https://${GH_TOKEN}@${GH_REF}/piccuss.github.io" hexo:hexo


env:
 global:
   - GH_REF: github.com/piccuss