language: java
jdk:
  - oraclejdk8

before_install:
  - git clone https://${GH_REF}/github.piccuss.io.git
script:
  - mvn test

after_script:
  - cd github.piccuss.io/source/_posts/
  - git add .
  - git commit -m"Travis auto commit"
  - git push --force "https://${GH_TOKEN}@${GH_REF}/github.piccuss.io" hexo:hexo


env:
 global:
   - GH_REF: github.com/piccuss